# Generated by Django 5.2.8 on 2026-01-13 17:11

from django.db import migrations


def remove_indexes_if_exist(apps, schema_editor):
    """Safely remove indexes if they exist."""
    db_alias = schema_editor.connection.alias
    
    # List of indexes to remove: (table_name, index_name)
    indexes_to_remove = [
        ('volunteer_app_activity', 'volunteer_a_act_datetime_idx'),
        ('volunteer_app_activity', 'volunteer_a_act_status_idx'),
        ('volunteer_app_activitysignup', 'volunteer_a_signup_status_idx'),
        ('volunteer_app_emailverification', 'volunteer_a_email_token_idx'),
        ('volunteer_app_emailverification', 'volunteer_a_email_expires_idx'),
        ('volunteer_app_qrscan', 'volunteer_a_qr_scanned_idx'),
        ('volunteer_app_user', 'volunteer_a_user_email_idx'),
        ('volunteer_app_user', 'volunteer_a_user_email_v_idx'),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for table_name, index_name in indexes_to_remove:
            # Check if index exists (SQLite specific)
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='index' AND name=?
            """, [index_name])
            if cursor.fetchone():
                try:
                    cursor.execute(f"DROP INDEX IF EXISTS {index_name}")
                except Exception:
                    pass  # Ignore if index doesn't exist


def reverse_remove_indexes(apps, schema_editor):
    """Reverse operation - indexes are not recreated."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0008_email_verification'),
    ]

    operations = [
        migrations.RunPython(remove_indexes_if_exist, reverse_remove_indexes),
    ]
