# Generated by Django 5.2.8 on 2026-01-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0009_fix_indexes'),
        ('volunteer_app', '0009_remove_activity_volunteer_a_act_datetime_idx_and_more'),
    ]

    operations = [
    ]
