# Generated by Django 5.2.8 on 2026-01-15 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0010_merge_20260114_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('checkin', 'Check-in'), ('checkout', 'Check-out')], max_length=10)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=200)),
                ('calculated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('device_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        # Note: Index removals are handled in migration 0009_remove_activity_...
        # These indexes may have already been removed, so we skip them here
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified_at',
        ),
        migrations.AddField(
            model_name='checkinout',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins_outs', to='volunteer_app.activity'),
        ),
        migrations.AddField(
            model_name='checkinout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins_outs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
        migrations.AddIndex(
            model_name='checkinout',
            index=models.Index(fields=['activity', 'user', 'check_type'], name='volunteer_a_activit_8404da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkinout',
            unique_together={('activity', 'user', 'check_type')},
        ),
    ]
