# Generated by Django 5.2.8 on 2026-01-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_app', '0011_checkinout_remove_emailverification_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='volunteer_a_act_datetime_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='volunteer_a_act_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitysignup',
            name='volunteer_a_signup_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='qrscan',
            name='volunteer_a_qr_scanned_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='volunteer_a_user_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='volunteer_a_user_email_v_idx',
        ),
    ]
